//SELECT all people from southampton --> 914
SELECT COUNT(*)
FROM TITANIC
WHERE TITANIC.EMBARKED_ID = (SELECT ID FROM EMBARKED WHERE EMBARKED.CITY = 'Southampton');

// Select all people with an unkown embarking --> 2
SELECT COUNT(*)
FROM TITANIC
WHERE TITANIC.EMBARKED_ID IS NULL;

// Select port and ticket of passenger lovell
SELECT TICKETS.NAME, EMBARKED.CITY, TITANIC.NAME
FROM TITANIC
         JOIN TICKETS ON TITANIC.TICKET_ID = TICKETS.ID
         JOIN EMBARKED ON TITANIC.EMBARKED_ID = EMBARKED.ID
WHERE TITANIC.NAME LIKE '%Lovell%';

//Get the count of people who embarked from each city
SELECT COUNT(*) as PASSENGERS, EMBARKED.CITY AS CITY
FROM TITANIC
         JOIN EMBARKED ON TITANIC.EMBARKED_ID = EMBARKED.ID
GROUP BY EMBARKED.CITY;

//Get name, ticket name and embarking of passenger 1014
SELECT EMBARKED.CITY AS CITY, TICKETS.NAME AS TICKET_NAME, TITANIC.NAME
FROM TITANIC
         JOIN EMBARKED ON EMBARKED.ID = TITANIC.EMBARKED_ID
         JOIN TICKETS ON TITANIC.TICKET_ID = TICKETS.ID
WHERE TITANIC.ID = 1014;

//Check which tickets were used by more than one person
SELECT COUNT(*) AS TIMES_USED, TICKETS.NAME AS TICKET_NUMBER
FROM TITANIC
         JOIN TICKETS ON TITANIC.TICKET_ID = TICKETS.ID
GROUP BY TICKETS.NAME
HAVING TIMES_USED > 1;

//Check if there are any people who embarked from different cities with the same ticket

SELECT EMBARKED.CITY, TITANIC.NAME, TICKETS.NAME
FROM TITANIC
         JOIN EMBARKED ON TITANIC.EMBARKED_ID = EMBARKED.ID
         JOIN TICKETS ON TITANIC.TICKET_ID = TICKETS.ID
WHERE TITANIC.TICKET_ID IN (
    SELECT TICKET_ID
    FROM TITANIC
    GROUP BY TICKET_ID
    HAVING COUNT(*) > 1
    )
  AND TITANIC.TICKET_ID IN (
    SELECT TICKET_ID
    FROM TITANIC
    GROUP BY TICKET_ID, EMBARKED_ID
    HAVING COUNT(DISTINCT EMBARKED_ID) > 1
    )